INSERT INTO CREDIT
VALUES (1, 1.0);
INSERT INTO CREDIT
VALUES (2, 2.0);
INSERT INTO CREDIT
VALUES (3, 1.5);
INSERT INTO TEACHER
VALUES (1, 'Pesho', 'PROFESSOR');
INSERT INTO TEACHER
VALUES (2, 'Nade', 'DOCENT');
INSERT INTO TEACHER
VALUES (3, 'Karamfil', 'ASSISTANT');
INSERT INTO TEACHER
VALUES (4, 'Bozman', 'ASSISTANT');
INSERT INTO TEACHER
VALUES (5, 'Gosho', 'ASSISTANT');
INSERT INTO TEACHER
VALUES (6, 'Tosho', 'ASSISTANT');
INSERT INTO COURSE
VALUES (1, 'Math', '1', '3');
INSERT INTO COURSE
VALUES (2, 'Lathin', '2', '2');
INSERT INTO COURSE
VALUES (3, 'English', '2', '1');
INSERT INTO COURSE
VALUES (4, 'German', '4', '3');
INSERT INTO COURSE
VALUES (5, 'Spanish', '6', '2');
INSERT INTO COURSE
VALUES (6, 'Medicine', '6', '3');
INSERT INTO COURSE
VALUES (7, 'Football', '5', '1');
INSERT INTO STUDENT
VALUES (1, 'Alex', 'ONE');
INSERT INTO STUDENT
VALUES (2, 'Denski', 'FOUR');
INSERT INTO STUDENT
VALUES (3, 'Kalina', 'TWO');
INSERT INTO STUDENT
VALUES (4, 'Mario', 'TWO');
INSERT INTO STUDENT
VALUES (5, 'BenJ', 'THREE');
INSERT INTO STUDENT_COURSE
VALUES (1, 1);
INSERT INTO STUDENT_COURSE
VALUES (1, 2);
INSERT INTO STUDENT_COURSE
VALUES (1, 3);
INSERT INTO STUDENT_COURSE
VALUES (2, 3);
INSERT INTO STUDENT_COURSE
VALUES (2, 2);
INSERT INTO STUDENT_COURSE
VALUES (3, 1);
INSERT INTO STUDENT_COURSE
VALUES (3, 3);
INSERT INTO STUDENT_COURSE
VALUES (4, 1);
INSERT INTO STUDENT_COURSE
VALUES (5, 2);
INSERT INTO STUDENT_COURSE
VALUES (5, 3);
INSERT INTO STUDENT_COURSE
VALUES (5, 6);
INSERT INTO STUDENT_COURSE
VALUES (5, 4);
INSERT INTO STUDENT_COURSE
VALUES (5, 5);
INSERT INTO STUDENT_COURSE
VALUES (3, 6);
INSERT INTO STUDENT_COURSE
VALUES (3, 5);
INSERT INTO STUDENT_COURSE
VALUES (1, 6);
INSERT INTO STUDENT_COURSE
VALUES (2, 4);
INSERT INTO STUDENT_COURSE
VALUES (2, 5);