INSERT INTO CREDIT
VALUES (1, 1.0);
INSERT INTO CREDIT
VALUES (2, 2.0);
INSERT INTO TEACHER
VALUES (1, 'Pesho', 'professor');
INSERT INTO TEACHER
VALUES (2, 'Nade', 'DOCENT');
INSERT INTO TEACHER
VALUES (3, 'Karamfil', 'ASSISTANT');
INSERT INTO COURSE
VALUES (1, 'Math', '1', '1');
INSERT INTO COURSE
VALUES (2, 'Lathin', '2', '2');
INSERT INTO COURSE
VALUES (3, 'English', '2', '1');
INSERT INTO STUDENT
VALUES (1, 'Alex', 'ONE');
INSERT INTO STUDENT
VALUES (2, 'Denski', 'FOUR');
INSERT INTO STUDENT
VALUES (3, 'Kalina', 'TWO');
INSERT INTO STUDENT
VALUES (4, 'Mario', 'TWO');
INSERT INTO STUDENT
VALUES (5, 'BenJ', 'THREE');
INSERT INTO COURSE_STUDENT
VALUES (1, 1);
INSERT INTO COURSE_STUDENT
VALUES (1, 2);
INSERT INTO COURSE_STUDENT
VALUES (1, 3);
INSERT INTO COURSE_STUDENT
VALUES (2, 3);
INSERT INTO COURSE_STUDENT
VALUES (2, 2);
INSERT INTO COURSE_STUDENT
VALUES (3, 1);
INSERT INTO COURSE_STUDENT
VALUES (3, 3);
INSERT INTO COURSE_STUDENT
VALUES (4, 1);
INSERT INTO COURSE_STUDENT
VALUES (5, 2);
INSERT INTO COURSE_STUDENT
VALUES (5, 3);
